[project]
name = "westside-careers"
config = "!{pnpm}/node_modules/@supabase/supabase-js"

[api]
endpoint = "http://127.0.0.1:54321"
api_url = "http://127.0.0.1:54321"

[db]
host = "127.0.0.1"
port = 54321
user = "postgres"
password = "postgres"
database = "postgres"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://westsidecareers.vercel.app"]
jwt_expiry = 3600
enable_signup = false